name: Deploy to Lambda

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: List directory contents (for debugging)
        run: ls -la   
          
      - name: Restore dependencies
        run: dotnet restore MyLambdaFunction.sln
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      
      - name: List src directory contents
        run: ls -la src
      
      - name: Publish Lambda Project
        run: dotnet publish src/MyLambdaFunction/MyLambdaFunction.csproj -c Release -o ./publish /p:PublishReadyToRun=false /p:GenerateRuntimeConfigurationFiles=true
        
      - name: Deploy to AWS Lambda
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Deploy Lambda function
        run: |
          cd publish
          zip -r ../function.zip *
          aws lambda update-function-code --function-name my-lambda-function --zip-file fileb://../function.zip
